---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 192.168.32.193:5000/app:0.0.2
          replicas: 2
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_ENV
              value: development
            - name: FLASK_APP
              value: app.py
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 128Mi
